title: KenYeo's repositories
description: uncovering trends, revealing insights

author: 
  name: KenYeoKP
  email: https://www.linkedin.com/in/kenyeokp/

theme: minima 
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# jekyll-theme-minimal
