title: KenYeo's repositories
description: uncovering trends, revealing insights


theme: minima 
plugins:
  - jekyll-feed
  - jekyll-seo-tag

social_links:
  - platform: github,         user_url: "https://KenYeoKP.github.io"
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/kenyeokp/" }

