title: KenYeo's posts and repositories
description: uncovering trends, revealing insights
url: "https://KenYeoKP.github.io/"
theme: minima 
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# jekyll-theme-minimal
